# Generated by Django 5.2.3 on 2025-09-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('model_file', models.CharField(max_length=255)),
                ('accuracy', models.FloatField()),
                ('dataset_size', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Entraînement du modèle',
                'verbose_name_plural': 'Entraînements du modèle',
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualite_enseignement', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Note de 1 à 5', verbose_name="Qualité d'enseignement")),
                ('charge_travail', models.IntegerField(help_text="Nombre d'heures par semaine", verbose_name='Charge de travail')),
                ('interactivite', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Note de 1 à 5', verbose_name='Interactivité')),
                ('type_cours', models.CharField(choices=[('présentiel', 'Présentiel'), ('distanciel', 'Distanciel'), ('hybride', 'Hybride')], max_length=20, verbose_name='Type de cours')),
                ('niveau_etudiant', models.CharField(choices=[('L1', 'Licence 1'), ('L2', 'Licence 2'), ('L3', 'Licence 3')], max_length=5, verbose_name='Niveau étudiant')),
                ('satisfaction', models.BooleanField(blank=True, null=True, verbose_name='Satisfait')),
                ('predicted_satisfaction', models.BooleanField(blank=True, null=True, verbose_name='Satisfaction prédite')),
                ('probability_satisfied', models.FloatField(blank=True, null=True, verbose_name='Probabilité de satisfaction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avis étudiant',
                'verbose_name_plural': 'Avis étudiants',
                'ordering': ['-created_at'],
            },
        ),
    ]
