# Generated by Django 5.2.3 on 2025-09-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modeltraining',
            options={'ordering': ['-training_date']},
        ),
        migrations.AlterModelOptions(
            name='studentfeedback',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='studentfeedback',
            name='satisfaction',
        ),
        migrations.AlterField(
            model_name='modeltraining',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='charge_travail',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='interactivite',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='niveau_etudiant',
            field=models.CharField(choices=[('L1', 'L1'), ('L2', 'L2'), ('L3', 'L3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='predicted_satisfaction',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='probability_satisfied',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='qualite_enseignement',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='studentfeedback',
            name='type_cours',
            field=models.CharField(choices=[('présentiel', 'Présentiel'), ('distanciel', 'Distanciel'), ('hybride', 'Hybride')], max_length=20),
        ),
    ]
